### PR TITLE
RWLock

### PR DESCRIPTION
**Pull request by alexander-gridnev**
RWLock implementation based on toro.Semaphore.

### CODE REVIEW

**Comment by ajdavis** [comment]
Hi, thanks for the contribution! I'm going to look at this soon.

**Comment by ajdavis** [comment]
Thanks for the contribution, sorry this took so long to merge!

I have two proposals:

1. I think it's surprising that max_readers defaults to 1, so the RWLock acts like a lock by default. Could you make another pull request that either removes max_readers, or sets its default to None ("no maximum")?
2. Toro is being merged into Tornado 4.2, but RWLock will not be included. We want Tornado 4.2's locks to match asyncio's locks closely, and asyncio has no RWLock, so Tornado won't. I propose that once you contribute the max_readers change to Toro, you take the resulting code (including my fixes) and spin it off as its own repository and package, the same way asyncio's RWLock is a separate package: https://github.com/aio-libs/aiorwlock

**Comment by alexander-gridnev** [comment]
Good ideas, I'll do separate package for tornado >=4.2. RWLock without max_readers is more complex, than current realization=) I will make it soon.

**Comment by ajdavis** [comment]
Great, thanks!

**Comment by ajdavis** [comment]
Toro 1.0 is released, with your RWLock as the major feature:

http://toro.readthedocs.org/en/stable/changelog.html#changes-in-version-1-0

Thanks again for your contribution!

Now, I recommend you:
* Copy my updated code for RWLock from Toro.
* Port it to use Tornado 4.2 instead of using Toro.
* Release it to PyPI as a separate package that depends on Tornado >= 4.2 and does **not** depend on Toro.
* Let me know -- you can comment here or email jesse@mongodb.com -- and I'll link to your PyPI package from Toro's documentation.
* Add a link to your package in [Tornado's wiki](https://github.com/tornadoweb/tornado/wiki/Links#helper-libraries--frameworks).

**Comment by ajdavis** [comment]
For the "port to Tornado 4.2" step, this guide helps (it should be a very small change in RWLock):

http://www.tornadoweb.org/en/stable/releases/v4.2.0.html#new-modules-tornado-locks-and-tornado-queues

**Comment by bdarnell** [comment]
I actually think it would be fine to add `RWLock` to `tornado.locks` even if `asyncio` doesn't have one yet. We want to be compatible with `asyncio` wherever possible, but we don't have to limit ourselves to the types that they have. (I also want to add an unbuffered channel type to `tornado.queues`).

**Comment by ajdavis** [comment]
Cool, in that case @alexander-gridnev feel free to offer a patch to Tornado, Ben and I will review it.

**Comment by alexander-gridnev** [comment]
Great news!

I will make a change soon.

**Pull request merged**
